### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: "Dexi - Pokémon scanner"
email: team@cardscanner.app
description: "Ready to unlock the true Pokémon card value of your collection?
<br/><br/>
Introducing the ultimate Pokémon card price scanner app, built for collectors who want instant insights into their cards’ worth. Whether you’re a casual fan or a serious investor, our app makes Pokémon card valuation effortless. Simply scan your card and get accurate, real-time pricing powered by trusted market data, including TCGplayer Pokémon listings.
<br/><br/>
From rare finds to everyday cards, you’ll always know the exact card Pokémon price, how much your Pokémon trading card is worth, and which ones belong on the list of the most valuable Pokémon cards. Track your collection, compare Pokémon trading card prices, and discover trends that reveal which cards are gaining value.
<br/><br/>
Stop guessing what your Pokémon cards cost and start managing your collection with confidence. Whether you’re checking Pokémon TCG worth, calculating your Pokémon trading card worth, or simply exploring card Pokémon value, this app gives you the knowledge every collector needs.
<br/><br/>
Turn your deck into data, your hobby into an investment, and your cards into clarity. Your journey to mastering Pokémon card valuation starts here."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://cardscanner.app"
theme_color: '#efeeff'
#twitter_username: TODO
#github_username:  TODO
#author: Prodigy AI
logo: ./assets/images/large-logo.webp
#twitter:
#  username: sandochee
social:
  name: Prodigy AI
  links:
    # TODO facebook, insta, tiktok
    - https://cardscanner.app
    - https://cardscanner.app
    - https://cardscanner.app

languages: [ "en" ]
ampdir: amp

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.webp
  - docs
